### ISSUE TITLE
需求：部署和使用说明

### ISSUE THREAD

**Issue by Njhlx** [RabbitTeam/exceptionless-webhooks#1]
非常抱歉打扰，第一次使用。

自行摸索几天，一直没找到部署和使用的方法。是否可以提供个交单的部署和使用说明？非常感谢。

**Comment by majian159** [comment]
这是一个基于.NET Core的项目，项目运行可以查看.NET Core Web文档：https://docs.microsoft.com/zh-cn/aspnet/core/host-and-deploy/?view=aspnetcore-2.1&tabs=aspnetcore2x
再者这个是exceptionless的webhook项目，可以用于发送钉钉通知，只需在query传入钉钉机器人的accessToken参数即可

**Comment by majian159** [comment]
https://github.com/exceptionless/Exceptionless/wiki/Integrations

**Comment by lanhouzi** [comment]
请问可否支持微信推送？

**Comment by majian159** [comment]
@lanhouzi 不支持
